### ISSUE TITLE
Add SSL

### ISSUE THREAD

**Issue by MathiasRenner** [kns-it/Docker-BlueSpice-Wiki#4]
I am having a hard time to add SSL support, I need help here. This is my status so far:

This is needed to add SSL support to the Dockerfile
```
# Add required packages for Let's encrypt SSL support
RUN echo deb "http://ftp.debian.org/debian jessie-backports main" >> /etc/apt/sources.list && \
      apt update && \
      apt install -y python-certbot-apache -t jessie-backports
```
When the container is up and running, I exec'ed into the container and ran 
`certbot --authenticator webroot --installer apache`

This commend exited without errors (and it said that everything was installed fine). However, I still weren't able to access the webpage via the browser using SSL. HTTP still worked fine.

Any ideas?

**Comment by prskr** [comment]
A more Docker-ish way would to use a reverse proxy to publish the service instead of including the certbot into the wiki container.

You could have a look at [Traefik](https://traefik.io). It handles all the automatic certificate issuing and has also support for advanced routing features.

Otherwise you'd need to do the whole SSL setup for the Apache webserver and a cron daemon that takes care of renewal of the certificates...

**Comment by MathiasRenner** [comment]
Let's go with traefik. Do you have a working suggestion at hand?
This is my work in progress as of now:

```
version: "3.3"

services:
  lb:
    image: traefik:latest
    restart: always
    command: --api \ 
             --acme.storage=/etc/traefik/acme.json \
             --logLevel=info \ 
             --entryPoints=${TRAEFIK_ENTRYPOINT_HTTP} \
             --entryPoints=${TRAEFIK_ENTRYPOINT_HTTPS} \
             --defaultentrypoints=${TRAEFIK_DEFAULT_ENTRYPOINTS} \
             --acme=${ACME_ENABLE} \
             --acme.entrypoint=https \
             --acme.domains="${ACME_DOMAINS}" 
             --acme.email="${ACME_EMAIL}" \
             --acme.httpChallenge \
             --acme.httpChallenge.entrypoint=http \            
             --docker \
             --docker.domain="${DOCKER_DOMAIN}" \
             --docker.endpoint="unix:///var/run/docker.sock" \
             --docker.watch=true \
             --docker.exposedbydefault="false" 
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./docker/traefik:/etc/traefik/
      - /var/run/docker.sock:/var/run/docker.sock
 
  bluespice:
    image: 'knsit/bluespice:latest'
    volumes:
      - ./data/config:/config
      - ./data/extensions:/extensions
      - ./data/web-data:/data
    environment:
      - "WIKI_URL=https://sustainable.it"
      - "WIKI_NAME=BlueSpice-Wiki"
      - "DB_USER=bluespice"
      - "DB_PASS=my5qlR00t#"
      - "DB_NAME=bluespice"
      - "DB_SERVER=mysql"
      - "ADMIN_LOGIN=admin"
      - "ADMIN_PASS=bluespice"
    labels:
      - "traefik.backend=bluespice"
      - "traefik.frontend.rule=Host:${TRAEFIK_HOST}"
      - "traefik.port=8081"
      - "traefik.enable=true"
    ports:
      - 8081:80
    restart: always
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - ./data/db-data/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=my5qlR00t#
      - MYSQL_DATABASE=bluespice
      - MYSQL_USER=bluespice
      - MYSQL_PASSWORD=my5qlR00t#
    ports:
      - 3306:3306
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
```
Whit this `.env` file:
```
ACME_ENABLE=true
ACME_EMAIL=mail@sustainable-it.com
ACME_DOMAINS=sustainable-it.com,www.sustainable-it.com

DOCKER_DOMAIN="www.sustainable-it.com"

TRAEFIK_DEFAULT_ENTRYPOINTS=https
TRAEFIK_ENTRYPOINT_HTTP="Name:http Address::80"
TRAEFIK_ENTRYPOINT_HTTPS="Name:https Address::443 TLS"
TRAEFIK_HOST=sustainable-it.com,www.sustainable-it.com
```

When I open the Website at HTTPS, the logs shows the error:
`bluespice_1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.4. Set the 'ServerName' directive globally to suppress this message`

Not sure what to set as ServerName. The IP will change, of course...

**Comment by prskr** [comment]
Normally you should be able to ignore the warning. It's a typical Apache thing.

The way I normally deploy Traefik in a single Docker host environment is documented [here](https://gist.github.com/baez90/bcdecdf81db3cf0ab2ebbe7578d5dad3).
I prefer to have a configuration file which I pass to the container over passing a lot of arguments but that does not really matter.
Furthermore I would recommend you to run Traefik independent of your wiki as you might want to add more containers to Traefik afterwards and for that you need a external network which you can add to your additional Docker-Compose stacks.

To tell Traefik that it should consider the wiki do something like this:

```yml
version: "3.6"

services:
  bluespice:
    image: 'knsit/bluespice:latest'
    volumes:
      - ./data/config:/config
      - ./data/extensions:/extensions
      - ./data/web-data:/data
    networks:
      - proxy
      - mysql
    environment:
      - "WIKI_URL=https://sustainable.it"
      - "WIKI_NAME=BlueSpice-Wiki"
      - "DB_USER=bluespice"
      - "DB_PASS=my5qlR00t#"
      - "DB_NAME=bluespice"
      - "DB_SERVER=mysql"
      - "ADMIN_LOGIN=admin"
      - "ADMIN_PASS=bluespice"
    labels:
      - "traefik.backend=bluespice"
      - "traefik.frontend.rule=Host:${TRAEFIK_HOST}"
      - "traefik.port=80"
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
    restart: always
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - ./data/db-data/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=my5qlR00t#
      - MYSQL_DATABASE=bluespice
      - MYSQL_USER=bluespice
      - MYSQL_PASSWORD=my5qlR00t#
    ports:
      - 3306:3306
    networks:
      - mysql
    restart: always

networks:
  mysql: {}
  proxy:
    external: true
```

I didn't try the `docker-compose.yml` now so please let me know if that is what you're looking for.
